### ISSUE TITLE
SSL

### ISSUE THREAD

**Issue by philippe44** [GioF71/spotconnect-airplay-docker#1]
There is no libssl.so or libcrypto.so at all? If this is a naming issue, I can fix that.

**Comment by philippe44** [comment]
See https://github.com/philippe44/SpotConnect/issues/23

**Comment by GioF71** [comment]
Hello, libssl is installed, here:

`libssl3 is already the newest version (3.0.11-1~deb12u2)`

No version libcrypto was installed, so I tried adding libcrypto++8. I have now:

`libcrypto++8 is already the newest version (8.7.0+git220824-1)`

But the non-static version does not start:

```
[07:23:56.194] main:1221 Starting spotraop version: v0.5.0 (Nov 10 2023 @ 22:13:28)

[07:23:56.196] Start:945 Cannot load SSL libraries
[07:23:56.197] main:1325 Cannot start, exiting

```

I am using debian stable-slim as the base image.
But I just tried the regular stable (no -slim suffix) and there is no change.

What other tests can I do?

Thank you!

**Comment by GioF71** [comment]
Also worth mentioning that libcrypt1 is already installed:

`libcrypt1 is already the newest version (1:4.4.33-2)`

**Comment by philippe44** [comment]
What is the name of libcrypto and libssl, exactly ?

**Comment by philippe44** [comment]
I will have to look tomorrow, but I'm surprised by the libs installed by that Debian. None of my Debian-derived use them, but the classical libssl.so and libcrypto.so

**Comment by GioF71** [comment]
I hope these will answer you question...

```
root@gruesome03:/# apt show libssl3   
Package: libssl3
Version: 3.0.11-1~deb12u2
Priority: optional
Section: libs
Source: openssl
Maintainer: Debian OpenSSL Team <pkg-openssl-devel@alioth-lists.debian.net>
Installed-Size: 6154 kB
Depends: libc6 (>= 2.34)
Homepage: https://www.openssl.org/
Download-Size: 2019 kB
APT-Manual-Installed: no
APT-Sources: http://deb.debian.org/debian-security stable-security/main amd64 Packages
Description: Secure Sockets Layer toolkit - shared libraries

```

```
root@gruesome03:/# apt show libcrypto++8
Package: libcrypto++8
Version: 8.7.0+git220824-1
Priority: optional
Section: libs
Source: libcrypto++
Maintainer: Laszlo Boszormenyi (GCS) <gcs@debian.org>
Installed-Size: 5076 kB
Depends: libc6 (>= 2.34), libgcc-s1 (>= 3.0), libstdc++6 (>= 11)
Homepage: https://www.cryptopp.com
Tag: role::shared-lib
Download-Size: 1150 kB
APT-Manual-Installed: yes
APT-Sources: http://deb.debian.org/debian stable/main amd64 Packages
Description: General purpose cryptographic library - shared library

```

```
root@gruesome03:/# apt-get install libssl3
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libssl3 is already the newest version (3.0.11-1~deb12u2).
libssl3 set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@gruesome03:/# apt show libssl3     
Package: libssl3
Version: 3.0.11-1~deb12u2
Priority: optional
Section: libs
Source: openssl
Maintainer: Debian OpenSSL Team <pkg-openssl-devel@alioth-lists.debian.net>
Installed-Size: 6154 kB
Depends: libc6 (>= 2.34)
Homepage: https://www.openssl.org/
Download-Size: 2019 kB
APT-Manual-Installed: yes
APT-Sources: http://deb.debian.org/debian-security stable-security/main amd64 Packages
Description: Secure Sockets Layer toolkit - shared libraries

N: There is 1 additional record. Please use the '-a' switch to see it
```

```
root@gruesome03:/# apt show libcrypt1
Package: libcrypt1
Version: 1:4.4.33-2
Priority: optional
Protected: yes
Important: yes
Section: libs
Source: libxcrypt
Maintainer: Marco d'Itri <md@linux.it>
Installed-Size: 239 kB
Depends: libc6 (>= 2.36)
Conflicts: libpam0g (<< 1.4.0-10)
Replaces: libc6 (<< 2.29-4)
Tag: role::shared-lib
Download-Size: 89.5 kB
APT-Manual-Installed: yes
APT-Sources: http://deb.debian.org/debian stable/main amd64 Packages
Description: libcrypt shared library
```

**Comment by GioF71** [comment]
> I will have to look tomorrow, but I'm surprised by the libs installed by that Debian. None of my Debian-derived use them, but the classical libssl.so and libcrypto.so

Which other base images would you suggest? I might switch of course...

**Comment by philippe44** [comment]
I'm more of an (k)Ubuntu guy but more recently I've switched everything to armbian because I can easily rebuild everything back to the good old days. And I have the same everywhere and a good set of desktops if I want one.

**Comment by GioF71** [comment]
I switched to ubuntu and finally made it work by installing the package 'libssl-dev'.
Of course with that package, also debian works. I am building an updated image right now.
Thank you for your support!
